### ISSUE TITLE
Attention matrix scale

### ISSUE THREAD

**Issue by gwoksansan** [lemon0830/RAN#3]
假设A矩阵大小为N×N，当句子长度大于N时，encoder和decoder会分别怎么处理？

**Comment by lemon0830** [comment]
我们目前的处理方法是将所有句子cut到最大长度发自我的iPhone------------------ 原始邮件 ------------------发件人: gwoksansan  ***@***.***>发送时间: 2022年1月18日 11:56收件人: lemon0830/RAN ***@***.***>抄送: Subscribed ***@***.***>主题: Re: [lemon0830/RAN] Attention矩阵固定长度的问题 (Issue #3)
假设A矩阵大小为N×N，当句子长度大于N时，encoder和decoder会分别怎么处理？

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/lemon0830/RAN/issues/3",
"url": "https://github.com/lemon0830/RAN/issues/3",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by gwoksansan** [comment]
求问：解码阶段控制目标端生成句长的方式是通过max-len-a与max-len-b控制吗？
其中，ax+b（x为源端句长）
