### ISSUE TITLE
Difference between two attention modules

### ISSUE THREAD

**Issue by gwoksansan** [lemon0830/RAN#5]
Is there any difference between RecRandomAttention and MultiHeadwithRecRandomAttention in thseq.modules ?
Which one is used in paper?

**Comment by lemon0830** [comment]
Recrandomattention 发自我的iPhone------------------ Original ------------------From: gwoksansan  ***@***.***>Date: Mon,Mar 7,2022 8:14 PMTo: lemon0830/RAN ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [lemon0830/RAN] Difference between two attention modules (Issue #5)
Are there any difference between RecRandomAttention and MultiHeadwithRecRandomAttention in thseq.modules ?
Which one is used in paper?

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/lemon0830/RAN/issues/5",
"url": "https://github.com/lemon0830/RAN/issues/5",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
