### ISSUE TITLE
using normal self-attention in 1st layer

### ISSUE THREAD

**Issue by gwoksansan** [lemon0830/RAN#6]
看到开源代码中有控制enc/dec的第一层不使用RAN而是标准的self-attention，
求问第一层是否使用RAN对质量影响大嘛？是否第一层使用标准attention效果会更好呢？

**Comment by lemon0830** [comment]
论文的最终模型第一层和其他层没有区别，第一层使用标准的attention效果没有显著提升。

**Comment by lemon0830** [comment]
那只是实验的时候做的尝试，论文中的结果都是所有层都替换成RAN的效果发自我的iPhone------------------ Original ------------------From: gwoksansan  ***@***.***>Date: Wed,Apr 20,2022 6:18 PMTo: lemon0830/RAN ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [lemon0830/RAN] using normal self-attention in 1st layer (Issue #6)
看到开源代码中有控制enc/dec的第一层不使用RAN而是标准的self-attention，
求问第一层是否使用RAN对质量影响大嘛？是否第一层使用标准attention效果会更好呢？

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/lemon0830/RAN/issues/6",
"url": "https://github.com/lemon0830/RAN/issues/6",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
